//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dic_Kato
    {
        public Dic_Kato()
        {
            this.Dic_Kato1 = new HashSet<Dic_Kato>();
            this.PlanFact = new HashSet<PlanFact>();
            this.PlanFact1 = new HashSet<PlanFact>();
            this.PlanFact2 = new HashSet<PlanFact>();
        }
    
        public int ID { get; set; }
        public string Label { get; set; }
        public string Name_1 { get; set; }
        public string Name_2 { get; set; }
        public string tempParent { get; set; }
        public Nullable<int> ParentID { get; set; }
    
        public virtual ICollection<Dic_Kato> Dic_Kato1 { get; set; }
        public virtual Dic_Kato Dic_Kato2 { get; set; }
        public virtual ICollection<PlanFact> PlanFact { get; set; }
        public virtual ICollection<PlanFact> PlanFact1 { get; set; }
        public virtual ICollection<PlanFact> PlanFact2 { get; set; }
    }
}
