//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dic_Contragents
    {
        public int ID { get; set; }
        public string BIN { get; set; }
        public string RNN { get; set; }
        public string NameRu { get; set; }
        public string NameKz { get; set; }
        public string AdressJur { get; set; }
        public string AdressFact { get; set; }
        public string Email { get; set; }
        public string Phones { get; set; }
        public Nullable<int> IDOked { get; set; }
        public string ShorNameRu { get; set; }
        public string ShorNameKz { get; set; }
        public Nullable<int> IDCountry { get; set; }
        public Nullable<int> IDKato { get; set; }
        public Nullable<int> IDKrp { get; set; }
        public int IDOriginal { get; set; }
        public Nullable<int> IDDuble { get; set; }
        public string TableSource { get; set; }
        public string ColumnID { get; set; }
        public Nullable<int> TypeContragent { get; set; }
    }
}
