//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dic_Mkee
    {
        public Dic_Mkee()
        {
            this.Dic_CertificatesDetail = new HashSet<Dic_CertificatesDetail>();
            this.PlanFact = new HashSet<PlanFact>();
        }
    
        public int ID { get; set; }
        public string Label { get; set; }
        public string Name_1 { get; set; }
        public string Name_2 { get; set; }
    
        public virtual ICollection<Dic_CertificatesDetail> Dic_CertificatesDetail { get; set; }
        public virtual ICollection<PlanFact> PlanFact { get; set; }
    }
}
