//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dic_Ens
    {
        public Dic_Ens()
        {
            this.Dic_Ens1 = new HashSet<Dic_Ens>();
            this.PlanFact = new HashSet<PlanFact>();
        }
    
        public int ID { get; set; }
        public string TypePurchase { get; set; }
        public string Label { get; set; }
        public string Kpved { get; set; }
        public string Unioncheck { get; set; }
        public string Name_1 { get; set; }
        public string Descript { get; set; }
        public string Mkee_name { get; set; }
        public string Mkee_label { get; set; }
        public string FileName { get; set; }
        public string SheetName { get; set; }
        public Nullable<int> RowNumber { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> IDKpved { get; set; }
    
        public virtual ICollection<Dic_Ens> Dic_Ens1 { get; set; }
        public virtual Dic_Ens Dic_Ens2 { get; set; }
        public virtual ICollection<PlanFact> PlanFact { get; set; }
    }
}
