//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dic_Kpved
    {
        public Dic_Kpved()
        {
            this.Dic_Kpved1 = new HashSet<Dic_Kpved>();
            this.PlanFact = new HashSet<PlanFact>();
        }
    
        public int ID { get; set; }
        public string Label { get; set; }
        public string Unioncheck { get; set; }
        public string Name_1 { get; set; }
        public string Name_2 { get; set; }
        public Nullable<int> IdTRUType { get; set; }
        public string Kpved_type_desc { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> CountSymbols { get; set; }
        public Nullable<int> CodeMkee { get; set; }
        public string ValueMkee { get; set; }
        public string Descr { get; set; }
        public string StandardName { get; set; }
    
        public virtual ICollection<Dic_Kpved> Dic_Kpved1 { get; set; }
        public virtual Dic_Kpved Dic_Kpved2 { get; set; }
        public virtual ICollection<PlanFact> PlanFact { get; set; }
    }
}
