//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dic_Oked
    {
        public int ID { get; set; }
        public string Label { get; set; }
        public string Name_1 { get; set; }
        public string Name_2 { get; set; }
        public string tempParent { get; set; }
        public Nullable<int> ParentID { get; set; }
    }
}
