//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dic_Certificates
    {
        public Dic_Certificates()
        {
            this.Dic_CertificatesDetail = new HashSet<Dic_CertificatesDetail>();
            this.PlanFact = new HashSet<PlanFact>();
        }
    
        public int ID { get; set; }
        public Nullable<int> KatoRef { get; set; }
        public Nullable<System.DateTime> Дата_сертификата { get; set; }
        public string Наименование_экспортера_рус { get; set; }
        public string Наименование_экспортера_каз { get; set; }
        public string Адрес_экспортера_рус { get; set; }
        public string Адрес_экспортера_каз { get; set; }
        public string БИН_экспортера { get; set; }
        public string КАТО { get; set; }
        public string Организационно_правовая_форма_рус { get; set; }
        public string Организационно_правовая_форма_каз { get; set; }
        public string email { get; set; }
        public string www { get; set; }
        public string tel { get; set; }
        public string ФИО_руководителя { get; set; }
        public string Наименование_импортера_рус { get; set; }
        public string Наименование_импортера_каз { get; set; }
        public string Адрес_импортера { get; set; }
        public string БИН_импортера { get; set; }
        public string Заявитель { get; set; }
        public string Транспорт { get; set; }
        public string Основание_для_выдачи { get; set; }
        public string ФИО { get; set; }
        public Nullable<double> Код_органа_выдачи { get; set; }
        public string Наименование_органа_выдачи { get; set; }
        public string Номер_сертификата { get; set; }
        public string Серия_сертификата { get; set; }
        public string lfn { get; set; }
        public Nullable<int> RowNumber { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> Wrong { get; set; }
    
        public virtual ICollection<Dic_CertificatesDetail> Dic_CertificatesDetail { get; set; }
        public virtual ICollection<PlanFact> PlanFact { get; set; }
    }
}
