//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dic_ContragentsCl
    {
        public Dic_ContragentsCl()
        {
            this.PlanFact = new HashSet<PlanFact>();
            this.PlanFact1 = new HashSet<PlanFact>();
        }
    
        public int ID { get; set; }
        public string BIN { get; set; }
        public string RNN { get; set; }
        public string NameRu { get; set; }
        public string NameKz { get; set; }
        public string AdressJur { get; set; }
        public string AdressFact { get; set; }
        public string Email { get; set; }
        public string Phones { get; set; }
        public Nullable<int> IDOked { get; set; }
        public string ShorNameRu { get; set; }
        public string ShorNameKz { get; set; }
        public Nullable<int> IDCountry { get; set; }
        public Nullable<int> IDKato { get; set; }
        public Nullable<int> IDKrp { get; set; }
        public Nullable<int> IDOriginal { get; set; }
        public Nullable<int> IDDuble { get; set; }
        public string TableSource { get; set; }
        public string ColumnID { get; set; }
        public Nullable<int> TypeContragent { get; set; }
        public string IINLeader { get; set; }
        public Nullable<bool> IsOTP { get; set; }
        public string FIOLeader { get; set; }
        public Nullable<bool> IsNationalCompany { get; set; }
        public Nullable<bool> IsInternationalCompany { get; set; }
        public Nullable<System.DateTime> DateRegister { get; set; }
        public Nullable<bool> IsFalseBusinessman { get; set; }
    
        public virtual ICollection<PlanFact> PlanFact { get; set; }
        public virtual ICollection<PlanFact> PlanFact1 { get; set; }
    }
}
