//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dic_Countries
    {
        public Dic_Countries()
        {
            this.PlanFact = new HashSet<PlanFact>();
            this.PlanFact1 = new HashSet<PlanFact>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public bool IsDeleted { get; set; }
        public string Names { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Alfa2 { get; set; }
        public string Alfa3 { get; set; }
    
        public virtual ICollection<PlanFact> PlanFact { get; set; }
        public virtual ICollection<PlanFact> PlanFact1 { get; set; }
    }
}
