//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dic_CertificatesNEW
    {
        public int ID { get; set; }
        public string Наименование_ОТП { get; set; }
        public string БИН { get; set; }
        public Nullable<int> IDContragent { get; set; }
        public Nullable<int> IDKpved { get; set; }
        public string Регион { get; set; }
        public string Адрес { get; set; }
        public string контактный_телефон { get; set; }
        public string Производимая_продукция_Описание_ { get; set; }
        public string Код_ЕНС_ТРУ { get; set; }
        public string Код_КП_ВЭД { get; set; }
        public string Код_ТНВЭД { get; set; }
        public Nullable<decimal> ДМС { get; set; }
        public string Номер_сертификата_СТ_KZ { get; set; }
        public string Дата_выдачи_сертификата { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> RowNumber { get; set; }
        public Nullable<System.DateTime> DateReportStart { get; set; }
        public Nullable<System.DateTime> DateReportEnd { get; set; }
    }
}
