//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dic_CertificatesDetail
    {
        public int ID { get; set; }
        public int IDCertificate { get; set; }
        public Nullable<int> MkeeRef { get; set; }
        public Nullable<int> KpvedRef { get; set; }
        public Nullable<int> TnvedRef { get; set; }
        public string ТНВЭД { get; set; }
        public string КПВЭД { get; set; }
        public string Упаковка { get; set; }
        public string Наименование_товара_рус { get; set; }
        public string Наименование_товара_каз { get; set; }
        public Nullable<double> Доля_КС__ { get; set; }
        public string Вес_нетто_брутто { get; set; }
        public Nullable<double> Кол_во { get; set; }
        public string МКЕИ { get; set; }
        public Nullable<double> Цена_за_1_ед { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> RowNumber { get; set; }
    
        public virtual Dic_Certificates Dic_Certificates { get; set; }
        public virtual Dic_Mkee Dic_Mkee { get; set; }
    }
}
