//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMER
{
    using System;
    using System.Collections.Generic;
    
    public partial class dimDate
    {
        public dimDate()
        {
            this.PlanFact = new HashSet<PlanFact>();
            this.PlanFact1 = new HashSet<PlanFact>();
            this.PlanFact2 = new HashSet<PlanFact>();
            this.PlanFact3 = new HashSet<PlanFact>();
            this.XLSX_CMER_Transactions = new HashSet<XLSX_CMER_Transactions>();
        }
    
        public System.DateTime IDDate { get; set; }
        public Nullable<int> IDYear { get; set; }
        public string DescrYear { get; set; }
        public Nullable<int> IDSemester { get; set; }
        public string DescrSemester { get; set; }
        public Nullable<int> IDQuarter { get; set; }
        public string DescrQuarter { get; set; }
        public Nullable<int> IDMonth { get; set; }
        public string DescrMonth { get; set; }
        public Nullable<int> IDDay { get; set; }
        public string DescrDay { get; set; }
    
        public virtual ICollection<PlanFact> PlanFact { get; set; }
        public virtual ICollection<PlanFact> PlanFact1 { get; set; }
        public virtual ICollection<PlanFact> PlanFact2 { get; set; }
        public virtual ICollection<PlanFact> PlanFact3 { get; set; }
        public virtual ICollection<XLSX_CMER_Transactions> XLSX_CMER_Transactions { get; set; }
    }
}
