//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMER
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanFact_Err
    {
        public int IDFact { get; set; }
        public string IDKpved { get; set; }
        public string Qty { get; set; }
        public string Volume { get; set; }
        public string IDMkee { get; set; }
        public string IDKatoDelivery { get; set; }
        public string IDContragentPurchaser { get; set; }
        public string IDContragentSupplier { get; set; }
        public string IDSource { get; set; }
        public string DateStart { get; set; }
        public string DateEnd { get; set; }
        public string Name { get; set; }
        public string IDTypePlanFact { get; set; }
        public string IDSkp { get; set; }
        public string KS { get; set; }
        public string IDCertificate { get; set; }
        public string NumCertificate { get; set; }
        public string IDEns { get; set; }
        public string IDTnved { get; set; }
        public string ErrorMessage { get; set; }
        public string CreatedDate { get; set; }
        public string UpdatedDate { get; set; }
        public string FilePath { get; set; }
        public string RowNumber { get; set; }
        public string SerialCertificate { get; set; }
        public string OtpLastYear { get; set; }
        public string IDCertificateDetail { get; set; }
        public string DateReportStart { get; set; }
        public string IssetInSource { get; set; }
        public string DateReportEnd { get; set; }
        public string ErrorCode { get; set; }
        public string ErrorColumn { get; set; }
        public string ContractNumber { get; set; }
        public string IDKatoPurchaser { get; set; }
        public string IDKatoSupplier { get; set; }
        public string IDCountryPurchaser { get; set; }
        public string IDCountrySupplier { get; set; }
        public string VolumeWNds { get; set; }
        public string Nds { get; set; }
        public Nullable<int> IdOriginal { get; set; }
        public string ValueMkee { get; set; }
        public string ValueKatoDelivery { get; set; }
        public string ValueKatoPurchaser { get; set; }
        public string ValueKatoSupplier { get; set; }
        public string ValueCountrySupplier { get; set; }
        public string ValueCountryPurchaser { get; set; }
        public string ValueKpved { get; set; }
        public string ValueTnved { get; set; }
        public string ValueSkp { get; set; }
    }
}
