//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMER
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPlanFactLists
    {
        public int IDFact { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string ctgSName { get; set; }
        public string ctgPName { get; set; }
        public string katoSName { get; set; }
        public string katoPName { get; set; }
        public string mkeeName { get; set; }
        public string kpvedName { get; set; }
        public string skpName { get; set; }
        public string countrySName { get; set; }
        public string countryPName { get; set; }
        public string truType { get; set; }
        public string srcName { get; set; }
    }
}
