//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMER
{
    using System;
    using System.Collections.Generic;
    
    public partial class XLSX_CMER_Transactions
    {
        public Nullable<int> IDSource { get; set; }
        public Nullable<System.DateTime> IDDate { get; set; }
        public Nullable<int> IDRegion { get; set; }
        public Nullable<long> IDCustomer { get; set; }
        public Nullable<int> IDCountrySupplier { get; set; }
        public Nullable<long> IDSupplier { get; set; }
        public Nullable<long> IDSegment { get; set; }
        public Nullable<int> IDTRUType { get; set; }
        public string Descr { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public long RECID { get; set; }
    
        public virtual dimDate dimDate { get; set; }
        public virtual XLSX_CMER_Contragents XLSX_CMER_Contragents { get; set; }
        public virtual XLSX_CMER_Contragents XLSX_CMER_Contragents1 { get; set; }
        public virtual XLSX_CMER_Countries XLSX_CMER_Countries { get; set; }
        public virtual XLSX_CMER_Regions XLSX_CMER_Regions { get; set; }
        public virtual XLSX_CMER_Segments XLSX_CMER_Segments { get; set; }
        public virtual XLSX_CMER_Sources XLSX_CMER_Sources { get; set; }
        public virtual XLSX_CMER_TRUTypes XLSX_CMER_TRUTypes { get; set; }
    }
}
